enum EventType {
  GATHERING = "GATHERING",
  MEETING = "MEETING",
  ANNOUNCEMENT = "ANNOUNCEMENT",
  MAINTENANCE = "MAINTENANCE",
  REMINDER = "REMINDER",
  WARNING = "WARNING",
}

export default EventType;
