enum MarkerType {
  EVENT = "EVENT",
  MEETING = "MEETING",
  ANNOUNCEMENT = "ANNOUNCEMENT",
  MAINTENANCE = "MAINTENANCE",
  REMINDER = "REMINDER",
  WARNING = "WARNING",
}

export default MarkerType;
